app = "kafka"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  KAFKA_ZOOKEEPER_CONNECT="149.248.218.77:2181"
  KAFKA_LISTENERS="PLAINTEXT://localhost:9092"
  KAFKA_HEAP_OPTS="-Xmx1024M -Xms1024M"

[build]
  image = "wurstmeister/kafka:latest"

[[services]]
  internal_port = 9092
  protocol = "tcp"

  [[services.ports]]
    port = 9092

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source="kafka_data"
  destination="/data"