name: deploy-feeder-api

on:
  push:
    paths:
      - apps/feeder-api/**
      - .github/**
    branches:
      - main
      - eds/main

jobs:
  test-api:
    name: Test Feeder API
    uses: ./.github/workflows/reusable-test-go.yaml
    with:
      component: apps/feeder-api
  deploy-api:
    name: Deploy Feeder API
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      component: apps/feeder-api
    secrets:
      fly-api-token: ${{ secrets.FLY_API_TOKEN }}
    needs: [test-api]
