name: reusable-deploy

on:
  workflow_call:
    inputs:
      component:
        description: "The component to deploy. Must match the name of a directory in the root of the repo."
        required: true
        type: string
    secrets:
      fly-api-token:
        description: "The fly.io API token used to perform the deployment."
        required: true

env:
  FLY_API_TOKEN: ${{ secrets.fly-api-token }}

jobs:
  deploy:
    name: Deploy component
    defaults:
        run:
          working-directory: ${{ inputs.component }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only