name: test-feeder-api

on:
  pull_request:
    branches:
      - main
      - eds/main
      - "release/**"
      - "cicd/**"
      - dev
    paths:
      - apps/feeder-api/**
      - .github/**

jobs:
  test-api:
    name: Test API
    uses: ./.github/workflows/reusable-test-go.yaml
    with:
      component: apps/feeder-api
